### ISSUE TITLE
Error generating alignment for a mapped read

### ISSUE THREAD

**Issue by morungos** [capsid/capsid-webapp#73]
URL is: /mapped/alignment/539fb7ef1f37b45e54d5dfd3

```
assert mdActions.size() == 0
       |         |      |
       |         1      false
       [[MD_COPY, 0]]. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [alignment] of controller [ca.on.oicr.capsid.MappedController]  caused exception: Runtime error executing action
    at org.eclipse.jetty.servlet.ServletHolder.handle(ServletHolder.java:684)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1448)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:575)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:276)
    at org.eclipse.jetty.server.Dispatcher.forward(Dispatcher.java:103)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler$CachedChain.doFilter(ServletHandler.java:1419)
    at org.eclipse.jetty.servlet.ServletHandler.doHandle(ServletHandler.java:455)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:137)
    at org.eclipse.jetty.security.SecurityHandler.handle(SecurityHandler.java:557)
    at org.eclipse.jetty.server.session.SessionHandler.doHandle(SessionHandler.java:231)
    at org.eclipse.jetty.server.handler.ContextHandler.doHandle(ContextHandler.java:1075)
    at org.eclipse.jetty.servlet.ServletHandler.doScope(ServletHandler.java:384)
    at org.eclipse.jetty.server.session.SessionHandler.doScope(SessionHandler.java:193)
    at org.eclipse.jetty.server.handler.ContextHandler.doScope(ContextHandler.java:1009)
    at org.eclipse.jetty.server.handler.ScopedHandler.handle(ScopedHandler.java:135)
    at org.eclipse.jetty.server.handler.HandlerWrapper.handle(HandlerWrapper.java:116)
    at org.eclipse.jetty.server.Server.handle(Server.java:370)
    at org.eclipse.jetty.server.AbstractHttpConnection.handleRequest(AbstractHttpConnection.java:489)
    at org.eclipse.jetty.server.AbstractHttpConnection.headerComplete(AbstractHttpConnection.java:949)
    at org.eclipse.jetty.server.AbstractHttpConnection$RequestHandler.headerComplete(AbstractHttpConnection.java:1011)
    at org.eclipse.jetty.http.HttpParser.parseNext(HttpParser.java:644)
    at org.eclipse.jetty.http.HttpParser.parseAvailable(HttpParser.java:235)
    at org.eclipse.jetty.server.AsyncHttpConnection.handle(AsyncHttpConnection.java:82)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint.handle(SelectChannelEndPoint.java:668)
    at org.eclipse.jetty.io.nio.SelectChannelEndPoint$1.run(SelectChannelEndPoint.java:52)
    at org.eclipse.jetty.util.thread.QueuedThreadPool.runJob(QueuedThreadPool.java:608)
    at org.eclipse.jetty.util.thread.QueuedThreadPool$3.run(QueuedThreadPool.java:543)
    at java.lang.Thread.run(Thread.java:724)
Caused by: org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Runtime error executing action
    ... 44 more
Caused by: java.lang.reflect.InvocationTargetException
    ... 44 more
Caused by: Assertion failed: 

assert mdActions.size() == 0
       |         |      |
       |         1      false
       [[MD_COPY, 0]]

    at ca.on.oicr.capsid.SequenceService.calculateAlignment(SequenceService.groovy:249)
    at ca.on.oicr.capsid.MappedService.getSplitAlignment(MappedService.groovy:81)
    at ca.on.oicr.capsid.MappedController.alignment(MappedController.groovy:63)
    ... 44 more
```

**Comment by morungos** [comment]
And another one: 

```
2014-06-27 13:41:08,164 [qtp1498909817-20] ERROR errors.GrailsExceptionResolver  - PowerAssertionError occurred when processing request: [GET] /mapped/alignment/53a1475ed5f33a07daea3ea0
assert mdActions[0][0] == MD_INSERT
       |        |  |   |  |
       |        |  |   |  MD_INSERT
       |        |  |   false
       |        |  MD_COPY
       |        [MD_COPY, 0]
       [[MD_COPY, 0], [MD_INSERT, G], [MD_COPY, 5], [MD_REPLACE, A], [MD_COPY, 0], [MD_REPLACE, T], [MD_COPY, 2], [MD_REPLACE, A], [MD_COPY, 3], [MD_REPLACE, C], [MD_COPY, 0], [MD_REPLACE, T], [MD_COPY, 14], [MD_REPLACE, G], [MD_COPY, 0], [MD_REPLACE, A], [MD_COPY, 1], [MD_REPLACE, A], [MD_COPY, 7], [MD_REPLACE, A], [MD_COPY, 3], [MD_REPLACE, C], [MD_COPY, 0], [MD_REPLACE, A], [MD_COPY, 1], [MD_REPLACE, G], [MD_COPY, 2], [MD_REPLACE, G], [MD_COPY, 3], [MD_REPLACE, G], [MD_COPY, 5], [MD_INSERT, AAGT], [MD_COPY, 2], [MD_REPLACE, A], [MD_COPY, 5], [MD_REPLACE, C], [MD_COPY, 0], [MD_REPLACE, T], [MD_COPY, 5]]. Stacktrace follows:
org.codehaus.groovy.grails.web.servlet.mvc.exceptions.ControllerExecutionException: Executing action [alignment] of controller [ca.on.oicr.capsid.MappedController]  caused exception: Runtime error executing action
```
